FROM ubi8/openjdk-8
#FROM ubi8/openjdk-11
ENV JAVA_OPTIONS=-Dquarkus.http.host=0.0.0.0
COPY target/lib/* /deployments/lib/
COPY target/*-runner.jar /deployments/app.jar
ENTRYPOINT [ "/usr/bin/java","-jar", "/deployments/app.jar" ]
